version: '3.8'

services:
  # QA Backend
  chapter-organizer-qa:
    build:
      context: .
      dockerfile: Dockerfile.qa
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=qa
    volumes:
      # Mount QA data directory for persistence
      - ./qa-data:/app/qa-data
      # Mount database exports for easy backup/restore
      - ./database-exports:/app/database-exports
      # Mount scripts
      - ./scripts:/app/scripts
    networks:
      - qa-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # QA Frontend (Optional - if you want to serve the frontend via Docker too)
  chapter-organizer-frontend-qa:
    build:
      context: ./frontend
      dockerfile: Dockerfile.qa
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:8080
      - NODE_ENV=development
    depends_on:
      - chapter-organizer-qa
    networks:
      - qa-network

  # Database Admin Tool (Optional - Adminer for database inspection)
  db-admin:
    image: adminer:4.8.1
    restart: always
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: chapter-organizer-qa:8080
    networks:
      - qa-network

networks:
  qa-network:
    driver: bridge

volumes:
  qa-data:
    driver: local